# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kbookmarks': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/knewstuff': 'Frameworks/6.24'
    'frameworks/knotifyconfig': 'Frameworks/6.24'
    'frameworks/kparts': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/ktextwidgets': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/kdoctools': 'Frameworks/6.24'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kpty': 'Frameworks/6.24'
    'frameworks/kglobalaccel': 'Frameworks/6.24'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 cppcheck-arguments:
  - --enable=warning,style,performance
#        - --suppress-xml=cppcheck-suppressions.xml
 cppcheck-ignore-files:
  - src/characters/CharacterWidth.src.cpp
#        - autotests
