/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -l Konsole -i konsole.h -a konsolescriptingadaptor -m org.kde.konsole.KonsoleScripting.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "konsolescriptingadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KonsoleScriptingAdaptor
 */

KonsoleScriptingAdaptor::KonsoleScriptingAdaptor(Konsole *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KonsoleScriptingAdaptor::~KonsoleScriptingAdaptor()
{
    // destructor
}

void KonsoleScriptingAdaptor::feedAllSessions(const QString &text)
{
    // handle method call org.kde.konsole.KonsoleScripting.feedAllSessions
    parent()->feedAllSessions(text);
}

void KonsoleScriptingAdaptor::sendAllSessions(const QString &text)
{
    // handle method call org.kde.konsole.KonsoleScripting.sendAllSessions
    parent()->sendAllSessions(text);
}


#include "konsolescriptingadaptor.moc"
