/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -l Konsole -i konsole.h -a konsolescriptingadaptor -m org.kde.konsole.KonsoleScripting.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KONSOLESCRIPTINGADAPTOR_H_1161949776
#define KONSOLESCRIPTINGADAPTOR_H_1161949776

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "konsole.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.konsole.KonsoleScripting
 */
class KonsoleScriptingAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.konsole.KonsoleScripting")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.konsole.KonsoleScripting\" >\n"
"    <method name=\"feedAllSessions\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\" />\n"
"    </method>\n"
"    <method name=\"sendAllSessions\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KonsoleScriptingAdaptor(Konsole *parent);
    virtual ~KonsoleScriptingAdaptor();

    inline Konsole *parent() const
    { return static_cast<Konsole *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void feedAllSessions(const QString &text);
    void sendAllSessions(const QString &text);
Q_SIGNALS: // SIGNALS
};

#endif
