/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.konsole.Session.Scripting.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "sessionscriptingadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SessionScriptingAdaptor
 */

SessionScriptingAdaptor::SessionScriptingAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SessionScriptingAdaptor::~SessionScriptingAdaptor()
{
    // destructor
}

void SessionScriptingAdaptor::feedSession(const QString &text)
{
    // handle method call org.kde.konsole.Session.Scripting.feedSession
    QMetaObject::invokeMethod(parent(), "feedSession", Q_ARG(QString, text));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->feedSession(text);
}

void SessionScriptingAdaptor::sendSession(const QString &text)
{
    // handle method call org.kde.konsole.Session.Scripting.sendSession
    QMetaObject::invokeMethod(parent(), "sendSession", Q_ARG(QString, text));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->sendSession(text);
}


#include "sessionscriptingadaptor.moc"
