/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -l TESession -i TESession.h -a sessionscriptingadaptor -m org.kde.konsole.SessionScripting.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "sessionscriptingadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SessionScriptingAdaptor
 */

SessionScriptingAdaptor::SessionScriptingAdaptor(TESession *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SessionScriptingAdaptor::~SessionScriptingAdaptor()
{
    // destructor
}

void SessionScriptingAdaptor::feedSession(const QString &text)
{
    // handle method call org.kde.konsole.SessionScripting.feedSession
    parent()->feedSession(text);
}

void SessionScriptingAdaptor::sendSession(const QString &text)
{
    // handle method call org.kde.konsole.SessionScripting.sendSession
    parent()->sendSession(text);
}


#include "sessionscriptingadaptor.moc"
