/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.konsole.Session.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef SESSIONADAPTOR_H_252641149593211
#define SESSIONADAPTOR_H_252641149593211

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.konsole.Session
 */
class SessionAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.konsole.Session")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.konsole.Session\" >\n"
"    <method name=\"closeSession\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"sendSignal\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"      <arg direction=\"in\" type=\"b\" name=\"signal\" />\n"
"    </method>\n"
"    <method name=\"clearHistory\" />\n"
"    <method name=\"renameSession\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\" />\n"
"    </method>\n"
"    <method name=\"sessionName\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"sessionPID\" >\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"schema\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"setSchema\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"schema\" />\n"
"    </method>\n"
"    <method name=\"encoding\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"setEncoding\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"encoding\" />\n"
"    </method>\n"
"    <method name=\"keytab\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"setKeytab\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"encoding\" />\n"
"    </method>\n"
"    <method name=\"font\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"setFont\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"encoding\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SessionAdaptor(QObject *parent);
    virtual ~SessionAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void clearHistory();
    bool closeSession();
    QString encoding();
    QString font();
    QString keytab();
    void renameSession(const QString &name);
    QString schema();
    bool sendSignal(bool signal);
    QString sessionName();
    int sessionPID();
    void setEncoding(const QString &encoding);
    void setFont(const QString &encoding);
    void setKeytab(const QString &encoding);
    void setSchema(const QString &schema);
Q_SIGNALS: // SIGNALS
};

#endif
