all: clear
	cp config/var/* .
	cp config/static/* .
	aclocal
	autoheader
	autoconf
	automake

clear:
	for i in *; do if [ -f $$i ]; then rm $$i; fi; done
	cp -f config/var/Makefile.cvs .
	rm -Rf src/.deps
	rm -f src/Makefile.in
	rm -f src/Makefile
	rm -f other/Makefile.in
	rm -f other/Makefile
	rm -f doc/Makefile.in
	rm -f doc/Makefile
